source "https://rubygems.org"

# Gemfile.lock / Bundler 2.7+ require Ruby 3.2 or newer. Use Homebrew Ruby on macOS
# (system Ruby 2.6 is too old). See AGENTS.md — Local Ruby setup.
ruby ">= 3.2.0"

# Updated gems (individual for updates)
gem "jekyll", "~> 4.4"
gem "kramdown", "~> 2.5"
gem "liquid", "~> 4.0"
gem "nokogiri", "~> 1.19"
gem "public_suffix", "~> 5.0"

# GitHub Pages dependencies (compatible versions)
gem "commonmarker", "~> 0.23"
gem "html-pipeline", "~> 2.14"
gem "jekyll-sass-converter", "~> 3.0"
gem "jekyll-watch", "~> 2.2"
gem "rouge", "~> 3.30"
gem "terminal-table", "~> 1.8"
gem "mercenary", "~> 0.3"
gem "minima", "~> 2.5"
gem "unicode-display_width", "~> 1.8"

# GitHub Pages themes and plugins
gem "github-pages-health-check", "~> 1.19"
gem "jekyll-avatar", "~> 0.8"
gem "jekyll-coffeescript", "~> 1.2"
gem "jekyll-default-layout", "~> 0.1"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-gist", "~> 1.5"
gem "jekyll-github-metadata", "~> 2.16"
gem "jekyll-include-cache", "~> 0.2"
gem "jekyll-mentions", "~> 1.6"
gem "jekyll-optional-front-matter", "~> 0.3"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-readme-index", "~> 0.3"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-relative-links", "~> 0.6"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-swiss", "~> 1.0"
gem "jekyll-theme-architect", "~> 0.2"
gem "jekyll-theme-cayman", "~> 0.2"
gem "jekyll-theme-dinky", "~> 0.2"
gem "jekyll-theme-hacker", "~> 0.2"
gem "jekyll-theme-leap-day", "~> 0.2"
gem "jekyll-theme-merlot", "~> 0.2"
gem "jekyll-theme-minimal", "~> 0.2"
gem "jekyll-theme-modernist", "~> 0.2"
gem "jekyll-theme-primer", "~> 0.6"
gem "jekyll-theme-slate", "~> 0.2"
gem "jekyll-theme-tactile", "~> 0.2"
gem "jekyll-theme-time-machine", "~> 0.2"
gem "jekyll-titles-from-headings", "~> 0.5"
gem "jemoji", "~> 0.13"

gem "webrick", "~> 1.8"
